// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeWeb;

#nullable disable

namespace ClinicAppointmentSystem.Migrations
{
    [DbContext(typeof(ClinicDbContent))]
    [Migration("20250921132614_CreateProductsTable")]
    partial class CreateProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClinicAppointmentSystem.Models.ClinicDb", b =>
                {
                    b.Property<string>("appointmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("appointmentId");

                    b.ToTable("datas");
                });
#pragma warning restore 612, 618
        }
    }
}
